### ISSUE TITLE
Disponibilidade de lançar dias e horas unitárias. 

### ISSUE THREAD

**Issue by JoaoMFerreira** [mfsuzigan/gp-bot#1]
Gostaria que fosse lançando apenas os dias que eu escolher e as horas tbm. 

Exemplo em um dia que fosse dado atestado, não posso lançar 8h naquele dia

**Comment by mfsuzigan** [comment]
O caso de uso já é atendido desde a versão 1.0.0. 

Utilize neste caso a opção de **ignorar dias**:
- no console, na opção **Não lançar estes dias**, informe o dia ou dias, separados por vírgula, que não deseja lançar. Exemplo: 2, 13, 25.
- via linha de comando, similarmente, informe o dia ou dias no parâmetro `--skipdays`. Exemplos: 

  - `java -jar gp-bot.jar --skipdays=2` para não lançar o dia 2; 
  - `java -jar gp-bot.jar --skipdays='2, 13, 25'` para não lançar os dias 2, 13 e 25.

Observe que no caso de múltiplos dias devem ser utilizadas aspas.
